### ISSUE TITLE
您写的fcgi-client与jetty给出的fcgi-client有什么不同的地方？

### ISSUE THREAD

**Issue by Glacier759** [wuyunfeng/Java-FastCGI-Client#1]
看到po主是中国人🇨🇳我就打汉字了（其实是英语渣

我对fastcgi不是很了解，现在有个需求就是要通过fastcgi与php-fpm去做通信，发现了po主贡献的框架，同时我还发现了jetty也提供了一个fcgi的client

实际操作中po主提供的代码是可正常work的，但是jetty给出的玩儿不起来，所以想向po主求助解惑这二者有何区别？

jetty-fcgi-client -> https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-fcgi/fcgi-client

**Comment by wuyunfeng** [comment]
Jetty对fastcgi的支持没关注过。粗略看了一眼，jetty好像是通过http协议传输fastcgi协议构造的数据。fastcgi协议和http协议只是不同的通信协议，Jetty好像是HTTP+fastcig

**Comment by Glacier759** [comment]
所以不work的原因是php-fpm无法解析http协议么？顺便问一下po主有什么能够了解fastcgi协议的好的资料么：）

**Comment by wuyunfeng** [comment]
php-fpm 不支持http协议，php-fpm是严格的fastcgi协议。两者是并列关系。fastcgi以前有官网可以完整的看到整个协议，现在官网好像打不开了。这个严格意义上并不能叫框架，有需要优化的地方

**Comment by wuyunfeng** [comment]
php-fpm是严格的fastcgi协议。两者是并列关系。fastcgi以前有官网可以完整的看到整个协议，现在官网好像打不开了。这个严格意义上并不能叫框架，有需要优化的地方

**Comment by Glacier759** [comment]
我这样理解有没有问题：nginx实际上起了一个fastcgi的client的作用，php-fpm是fastcgi的server端，php-fpm接收到nginx的消息执行相应的.php然后将结果返还。

jetty-fcgi-client不worker的原因是因为它是通过http来传输fastcgi协议，所以只有jetty-cgi-server才能从外面包的http中解析出fastcgi再来执行.php？

**Comment by Glacier759** [comment]
po主在这里应该是用java实现了：https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_fastcgi_module.c ？

**Comment by wuyunfeng** [comment]
1. nginx那个角色你的理解是正确的
2. jetty-fcgi-client 不work我没自习看代码，但是从命名上看如你所说
你可以从代码中直接看出fcgi协议的格式

**Comment by wuyunfeng** [comment]
1.nginx那个角色你的理解是正确的
2.jetty-fcgi-client 不work我没仔细看代码，但是从命名上看如你所说
你可以从代码中直接看出fcgi协议的格式

**Comment by Glacier759** [comment]
感谢po主：）

po主在写fcgi-client的时候是参考了什么资料么，我也想学习一下：）

**Comment by wuyunfeng** [comment]
参考了fastcgi官网。。。

**Comment by wuyunfeng** [comment]
fcgi只是个协议

**Comment by Glacier759** [comment]
官网GG。。。

**Comment by wuyunfeng** [comment]
😄😄😄

**Comment by 769344359** [comment]
http://www.mit.edu/~yandros/doc/specs/fcgi-spec.html

**Comment by 769344359** [comment]
请问 fast cgi 是 可以复用一个连接吗？
还是说每次都要不一样的socket

**Comment by wuyunfeng** [comment]
@769344359  nginx 和 fastcgi的连接是短链接的形式，处理完就断开，不会复用。fastcgi本身是可以复用的。

**Comment by 769344359** [comment]
谢谢 @wuyunfeng

**Comment by 769344359** [comment]
可是nginx 有 这个配置   fastcgi_keep_conn

**Comment by wuyunfeng** [comment]
@769344359 fastcgi的begin header里面有一个flag位标记是否长链接，不过仅仅修改这些（包括添加fastcgi_keep_conn）还是不会起作用，估计需要修改源码

**Comment by wuyunfeng** [comment]
@769344359  fastcgi的begin header里面有一个flag位标记是否长链接，不过仅仅修改这些（包括添加fastcgi_keep_conn）还是不会起作用，估计需要修改源码。不建议使用长链接，也需要php-fpm等支持
